import os
import logging
import discord
from discord import app_commands
from discord.ext import commands
from image_processing import extract_text_from_image, parse_bet_details
from ai_analysis import generate_analysis

# Basic logging
logging.basicConfig(level=logging.INFO)
log = logging.getLogger("gotlockz")

# Read token and guild from environment
DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
GUILD_ID = int(os.getenv("GUILD_ID", "0"))

# Create intents – we only need default intents for slash commands
intents = discord.Intents.default()
bot = commands.Bot(command_prefix="!", intents=intents)
tree = bot.tree

@bot.event
async def on_ready():
    log.info(f"GotLockz bot logged in as {bot.user} (ID: {bot.user.id})")
    log.info(f"Registering slash commands to guild {GUILD_ID}…")

    guild = discord.Object(id=GUILD_ID)
    tree.copy_global_to(guild=guild)
    await tree.sync(guild=guild)

    log.info("Slash commands synced.")

@tree.command(
    name="postpick",
    description="Register a pick and post it to your chosen channel",
    guild=discord.Object(id=GUILD_ID)
)
@app_commands.describe(
    units="How many units (e.g. 1.0) to wager on this pick",
    channel="Which channel to post the pick in"
)
async def postpick(interaction: discord.Interaction, units: float, channel: discord.TextChannel):
    await interaction.response.defer(ephemeral=True)

    embed = discord.Embed(
        title="\U0001F4E3 New Pick Posted!",
        description=f"**Units:** {units}\n**Picked by:** {interaction.user.mention}"
    )
    embed.set_footer(text="Good luck! \U0001F340")

    await channel.send(embed=embed)

    await interaction.followup.send(
        f"\u2705 Your pick of **{units} units** has been posted in {channel.mention}.",
        ephemeral=True
    )

@tree.command(
    name="analyze_bet",
    description="Upload a bet slip image to generate an AI-backed breakdown",
    guild=discord.Object(id=GUILD_ID)
)
@app_commands.describe(
    image="Upload an image of your MLB bet slip"
)
async def analyze_bet(interaction: discord.Interaction, image: discord.Attachment):
    await interaction.response.defer(ephemeral=True)

    image_path = f"/tmp/{image.filename}"
    await image.save(image_path)

    try:
        text = extract_text_from_image(image_path)
        bet_details = parse_bet_details(text)
        analysis = generate_analysis(bet_details)

        embed = discord.Embed(title="\U0001F52E Bet Analysis Report")
        for key, value in bet_details.items():
            embed.add_field(name=key.capitalize(), value=value, inline=False)
        embed.add_field(name="AI Analysis", value=analysis, inline=False)
        embed.set_footer(text="Generated by GotLockz AI \U0001F916")

        await interaction.followup.send(embed=embed, ephemeral=False)

    except Exception as e:
        log.error(f"Failed to process bet image: {e}")
        await interaction.followup.send("\u274C Failed to analyze the bet slip. Please make sure the image is clear and try again.", ephemeral=True)

if __name__ == "__main__":
    if DISCORD_TOKEN is None or GUILD_ID == 0:
        log.error("DISCORD_TOKEN or GUILD_ID not set in environment!")
        exit(1)

    bot.run(DISCORD_TOKEN)
