import os

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
MLB_STATS_API_KEY = os.getenv("MLB_STATS_API_KEY")
THE_ODDS_API_KEY = os.getenv("THE_ODDS_API_KEY")
API_SPORTS_KEY = os.getenv("API_SPORTS_KEY")
JSON_ODDS_KEY = os.getenv("JSON_ODDS_KEY")
GOOGLE_SHEETS_JSON_PATH = os.getenv("GOOGLE_SHEETS_CREDENTIALS_JSON")
TESSERACT_CMD_PATH = os.getenv("TESSERACT_CMD_PATH", "/usr/bin/tesseract")
DAILY_SUMMARY_CHANNEL_ID = os.getenv("DAILY_SUMMARY_CHANNEL_ID")
VALUE_THRESHOLD = float(os.getenv("VALUE_THRESHOLD", 0.05))
SHEETS_SPREADSHEET_ID = os.getenv("SHEETS_SPREADSHEET_ID")
