version: '3.8'
services:
  gotlockz-bot:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MLB_STATS_API_KEY=${MLB_STATS_API_KEY}
      - THE_ODDS_API_KEY=${THE_ODDS_API_KEY}
      - API_SPORTS_KEY=${API_SPORTS_KEY}
      - JSON_ODDS_KEY=${JSON_ODDS_KEY}
      - GOOGLE_SHEETS_CREDENTIALS_JSON=${GOOGLE_SHEETS_CREDENTIALS_JSON}
      - TESSERACT_CMD_PATH=/usr/bin/tesseract
      - SHEETS_SPREADSHEET_ID=${SHEETS_SPREADSHEET_ID}
      - DAILY_SUMMARY_CHANNEL_ID=${DAILY_SUMMARY_CHANNEL_ID}
      - VALUE_THRESHOLD=${VALUE_THRESHOLD}
    command: python bot.py
  daily-summary:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SHEETS_SPREADSHEET_ID=${SHEETS_SPREADSHEET_ID}
      - DAILY_SUMMARY_CHANNEL_ID=${DAILY_SUMMARY_CHANNEL_ID}
      - VALUE_THRESHOLD=${VALUE_THRESHOLD}
    command: python scripts/daily_summary.py
